### ISSUE TITLE
camera_thumbnail deprecated error 

### ISSUE THREAD

**Issue by Rrapa** [denysdovhan/vacuum-card#160] opened 2020-12-18 11:44 UTC
**Before submitting a bug**

[X ] I updated to the latest version available
[X ] I cleared the cache of my browser

**Describe the bug**
WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated

I'm flooded with that warning above. When I removed add in it stops. Can you please have a look? 

**Versions:**

- Release: [1.13]
- Browser: [any]
- HomeAssistant version: [2020.12.7 - but same issue on previous version as well]

**Comment by gmkrib** [comment] 2020-12-31 09:19
Same here, this appears when you will use the live map.

**Comment by DendelX** [comment] 2021-01-28 14:03
same here... isn't this card maintained?

**Comment by denysdovhan** [comment] 2021-02-02 14:46
This is a deprecation warning inside the HA. AFAIK HA dev docs do not provide any alternative yet.

We have to live with it someone finds an alternative solution.

**Comment by denysdovhan** [comment] 2021-02-02 14:57
Duplicate of #132

**Closed by denysdovhan** 2021-02-02 14:57 UTC
Labels: bug, help wanted
