### ISSUE TITLE
Action icons have disappeared 

### ISSUE THREAD

**Issue by bachoo786** [denysdovhan/vacuum-card#57] opened 2020-05-20 12:07 UTC
**Before submitting a bug**

Yes I updated to the latest version available
Yes I cleared the cache of my browser

I have just installed the latest version of this card and I have updated HA to 0.110. However the action icons have disappeared but the actions are still clickable and execute the script etc.

Please see the screenshot below from my mobile. 

![Screenshot_20200520-130129_Home Assistant](https://user-images.githubusercontent.com/6251030/82444251-d953a480-9a9a-11ea-8b16-90a955218983.jpg)

I am using official HA Android app on my android. This problem persists on my Windows computer on chrome. I have cleared the cache but the issue remains.

Thanks.

**Comment by andriej** [comment] 2020-05-20 15:32
Can confirm, same here. Probably it's connected with icon-update in frontend since 0.110.0

**Comment by luisrcastillo** [comment] 2020-05-20 17:53
Can also confirm buttons don't show on 0.110.0

**Comment by schliflo** [comment] 2020-05-20 18:43
This likely hast to do with the icon loading changes introduced in 0.110 --> https://www.home-assistant.io/blog/2020/05/20/release-110/#icons

**Comment by andreynet** [comment] 2020-05-20 20:41
Hello! 
It helped me replace in **vacuum-card.js**  - `paper-icon-button` on `ha-button-icon`

**Comment by krystiancharubin** [comment] 2020-05-21 03:32
#59

**Comment by murmelbahn** [comment] 2020-05-21 08:01
Converting from paper-icon-button to ha-button-icon helps but the space between the buttons is bigger then before. The problem is that you can't have the same amount of buttons in one row. In the mobile app it looks really ugly now because the card didn't generate a second row. In my opinion the card should resize the icons to show all of them in one row.

**Comment by krystiancharubin** [comment] 2020-05-21 11:05
Check the pr, I also removed extra padding around the icons that was there before.

**Comment by denysdovhan** [comment] 2020-05-21 12:18
Should be fixed by #59

**Closed by denysdovhan** 2020-05-21 12:18 UTC
Labels: bug
