### ISSUE TITLE
Latest Version Broke my Card

### ISSUE THREAD

**Issue by thorrrr** [denysdovhan/vacuum-card#376] opened 2022-04-27 20:02 UTC
**Before submitting a bug**

[ ] I updated to the latest version available  Yes installed today, 27 Apr 2022
[ ] I cleared the cache of my browser Done Several Times

**Describe the bug** 
No longer display see [here](https://xbackbone.daddycloud.co.uk/Piqa4/cUBIBITa00.jpg)

Version core-2022.4.7

Log

Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 20:10:31 (3 occurrences)
Last logged: 20:57:43

https: //mydomain/hacsfiles/button-card/button-card.js?hacstag=146194325342:547:3843 Uncaught TypeError: Cannot assign to read only property '0' of string 'none'
https: //mydomain/hacsfiles/vacuum-card/vacuum-card.js?hacstag=261291295260:1:22618 Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by camohob** [comment] 2022-04-27 20:08
+1
Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by denysdovhan** [comment] 2022-04-27 20:46
Should be fixed in the latest release.

**Closed by denysdovhan** 2022-04-27 20:46 UTC
Labels: bug

**Comment by pbranly** [comment] 2022-04-27 21:16
This is not fixed on my side

**Comment by denysdovhan** [comment] 2022-04-28 10:26
@pbranly make sure you are running the latest version. Clean the cache and check the result.

**Comment by pbranly** [comment] 2022-04-29 12:00
I did and finally it's working in my windows PC 
But it refuses and work in my IPad 
Regards
Philippe

**Comment by pbranly** [comment] 2022-05-01 07:53
I re confirm: there is no issue with windows but does not work on my IPad despite ca be clean, reboots , etc ...
Regards
Philippe

**Comment by thorrrr** [comment] 2022-05-01 08:32
Works perfectly fine on my iPad  suggest clearing cache

**Comment by pbranly** [comment] 2022-05-01 09:04
Hi
This is what I get from either IPad or Iphone 
After any cache clean
Regards
Philippe ![image](https://user-images.githubusercontent.com/22018509/166139274-95a2a061-4b8e-4fd1-be9f-abb6336c210d.png)

**Comment by pbranly** [comment] 2022-05-01 09:14
For information I use the IOS application for both iPad and iphone

**Comment by pbranly** [comment] 2022-05-01 11:42
I just try with safari ( so standard ha web access ) and it works as froM my PC
But from the IOS HA application it does not 
Regards
Philippe

**Comment by pbranly** [comment] 2022-05-01 11:44
http://192.168.1.8:8123/hacsfiles/vacuum-card/vacuum-card.js?hacstag=261291295262:1:22636 ReferenceError: Can't find variable: regeneratorRuntime

**Comment by pbranly** [comment] 2022-05-03 09:12
Hi could you reopen that issue ?
Or do you want me to open a new one ?
Just for remind the issue is with the IOS applets 
Regards
Philippe

**Comment by pbranly** [comment] 2022-05-08 16:30
Hi
Any news ?
It is a pity that your card does not work any more with the IOS applet
Regards
Philippe

**Comment by denysdovhan** [comment] 2022-05-08 16:53
Are you kidding me? It works for everyone but you: update to the latest version and clean the cache on your device (relogin or reinstall the app if necessary). The issue you are describing is fixed long ago. Just do what I told you.

**Comment by pbranly** [comment] 2022-05-08 17:03
I am very sorry to be the only one but I can assure you that I do not have any card since the last version on both my iPad and iphone with the home assistant applet 
I confirm that it is working on both iPad and iphone with Safari so with a browser but not with the applet.
![image](https://user-images.githubusercontent.com/22018509/167307081-b5b6475e-f478-47bc-9610-8c0d3fed11a2.png)

**Comment by pbranly** [comment] 2022-05-08 17:05
And this is the good result with the browser ![image](https://user-images.githubusercontent.com/22018509/167307193-c72d6afa-6692-44a0-86a4-becee0aa3350.jpeg)
